void Sh3_Graph_multiplex_test();
void Sh3_Graph_OGA_test();
void Sh3_Graph_CC_test();
void Sh3_Graph_eq_test();
void Sh3_Graph_shuffle_test();
void Sh3_Graph_sort_test();
void Sh3_Graph_PrefixAgg_test();
void Sh3_Graph_GraphSC_test();
void Sh3_Graph_CoGNN_test();